INSERT INTO jobs(company_id, title, url) VALUES
(2,   'Backend Software Engineer',                   'https://pganalyze.com/careers/backend-software-engineer'),
(3,   'Software Engineer',                           'https://jobs.lever.co/1password/b050d727-38a7-4083-bf18-ff3842e6de50'),                                                                     
(4,   'Junior Rust Developer',                       'https://apply.workable.com/singularity-data/j/12B7C7E7C1/'),                                                                                
(5,   'SE: Cloud Database',                          'https://jobs.ashbyhq.com/standard/b30ba21d-90d8-475f-991a-1d82c4af34e7'),                                                                   
(6,   'SE Rust Cloud (Services and Infrastructure',  'https://www.svix.com/careers/'),                                                                                                            
(7,   'Backend Engineer (Rust),',                     'https://www.datadoghq.com/careers/detail/?gh_jid=2169423'),
(8,   'Rust Engineer - Time-Series Database',        'https://loanpass.io/careerPage.html'),                                                                                                      
(9,   'Multiple Rust Positions',                     'https://apply.workable.com/fortanix/j/142ACAF269/'),                                                                                        
(10,  'Remote Software Engineer',                    'https://formlogic.breezy.hr/p/4fbae29d9d21-software-engineer-rust?&popup=true'),                                                            
(11,  'Software Engineer (Rust),',                    'https://www.apollographql.com/careers/job?id=afcdcb31-ce6b-4485-9987-3cc8bc361deb'),                                                        
(12,  'Rust Platform Engineer',                      'https://boards.greenhouse.io/stellate/jobs/4027858005'),
(13,  'Rust Engineer',                               'https://allspice.notion.site/allspice/AllSpice-Careers-3173d0cd518b4257b186ba5c8f34dc44?v=753295eeb6624e4c95eb40d7c6ff3040&p=844091d3def0467eb171b59ceb7ffa65'),      
(14,  'Backend Engineer',                            'https://www.fastly.com/about/jobs/apply/?gh_jid=4154106'),         
(15,  'Software Engineer - IAM',                     'https://apply.workable.com/seaplane/j/CEFCB5F5B8/'),                                                                                                     
(16,  '_FILLED_ Rust Software Engineer',             'https://www.linkedin.com/jobs/view/2922237969'),                                                                                                         
(17,  '_FILLED_ Back End Developer',                 'https://g.co/kgs/8wLGsj'),                                                                                                                               
(18,  '_FILLED_ Software Developer',                 'https://www.slight.co/jobs/software-engineer-rust'),                                                                                                     
(19,  '_FILLED_ Software Engineer',                  'https://metalbear.co/'),                                                     
(20,  'Intermediate Rust Engineer',                  'https://radicle.community/t/the-link-team-is-hiring/2908'),                              
(21,  'Various Positions',                           'https://grafbase.com/careers/backend-engineer'),                                       
(22,  'Backend Engineer',                            'https://jobs.lever.co/scytherobotics'),                                                  
(23,  'DevOps & Software Test Engineer',             'https://www.tangram.dev/jobs'),                                                         
(24,  '_FILLED_ Rust Developer',                     'https://bractlet.com/careers/'),                                                     
(25,  '_FILLED_',                                    'https://fusion.engineering/rust-engineer/'),                                            
(26,  '_FILLED Rust Engineer',                       'https://g.co/kgs/th9UKe'),                                                             -- _Lots_ of Experience Required:       
(27,  'Rust Engineer',                               'https://g.co/kgs/XtYhr3'),                                                                
(28,  'Sr. Rust Engineer',                           'https://g.co/kgs/HnRJef'),                                                            
(29,  'Senior Rust Developer',                       'https://g.co/kgs/YbwR6w'),                                                            
(30,  'Senior Rust Engineer',                        'https://g.co/kgs/omgEXd'),                                                                     
(31,  'Rust Expert',                                 'https://g.co/kgs/E2xi3o'),                                                                    
(32,  'Sr. Engineer - Rust, etc.',                   'https://yaak-technologies.jobs.personio.com/job/560318?display=en#apply'),                    
(33,  'Senior Software Engineer',                    'https://www.infinyon.com/careers/infrastructure-engineer-senior-level/'),                
(34,  'Sr. Rust Software Engineer',                  'https://boards.greenhouse.io/gro/jobs/4183159004?gh_src=24ac6dbd4us'),                
(35,  'Sr. Software Engineer',                       'https://jobs.lever.co/phylum/9eb9789b-9eff-438a-8910-95b3601d9692'),                       
(36,  'Senior Software Engineer',                    'https://immunant.com/jobs/'),                                                            
(37,  'Systems Programmer',                          'https://www.toyotaconnected.com/job?gh_jid=5881958002&did=4040990002'),                 -- **_MaYbE rUsT ?_**       
(38,  'Software Engineer',                           'https://www.estuary.dev/about/#backend'),                                            
(39,  'Backend Engineer',                            'https://www.getdbt.com/dbt-labs/open-roles/'),
(40,  'Whole Bunch',                                 'https://jobs.lever.co/onesignal/9e1d251c-c1f9-49c7-98e9-c883e519f902/apply'),        
(41,  'Senior Software Engineer',                    'https://jobs.lever.co/ntropy-network/5a587b64-7f97-4d75-be47-acf6394ed936'),         
(42,  'Backend Engineer',                            'https://discord.com/jobs/5834625002'),                                               
(43,  'Sr. Software Engineer - Safetey Engineering', 'https://boards.greenhouse.io/logdna/jobs/5025036002'),                               
(44,  'Senior Software Engineer, Backend',           'https://jobs.lever.co/stackblitz/7ccd2472-1416-4448-8642-e58e9b32e129'),             
(45,  'Software Engineer (Wasm OS + JS),',            'https://twitter.com/jrj/status/1530949737775411201'), 
(46,  '<insert disney job here',                     'disney url');