INSERT INTO companies (name, space, startup) VALUES
('PgAnalyze',          'database performance',              true),
('Cloudflare',         'content delivery',                  false),
('1Password',          'Password Managment',                false),
('Singularity',        'cloud streaming database',          true),
('Standard Cognition', 'automated checkout',                true),
('Svix',               'webhooksaaS',                       true),
('DataDog',            'monitoring',                        false),
('LoanPass',           'mortgage/lending',                  false),
('Fortanix',           'runtime encryption',                true),
('FormLogic',          'automated machining',               false),
('Apollo GraphQL',     'graphql tooling',                   true),
('Stellate',           'graphql edge computing',            true),
('AllSpice',           'github for hardware',               true),
('Fastly',             'edge computing',                    false),
('Seaplane',           'cloud services',                    true),
('ever.ag',            'agricultural risk management',      false),
('LaunchBadge',        'agency',                            false),
('slight.co',          'nocode & data visualization',       true),
('Metal Bear',         'pre-prod testing (mirrord)',        true),
('Radical/Link',       'local-first alternative to GitHub', true),
('Grafbase',           'graphql edge computing',            true),
('Scythe Robotics',    'robot lawn mower',                  false),
('Tangram',            'machine learning with rust',        true),
('Bractet',            'optimizing building energy use',    true),
('Fusion Engineering', 'drone controller',                  true),
('Select Star',        'data discovery',                    true),
('Crowd Strike',       'security',                          false),
('Workato',            'workflow & integration platform',   true),
('Ditto',              'p2p edge platform',                 true),
('Wasmer',             'web assembly runtime',              false),
('Ockam',              'e2e encryption as a service',       true),
('Yaak',               'driver coaching platform',          true),
('InfinityOn',         'event streaming platform',          true),
('GroIntelligence',    'data analysis and modeling for ag', false),
('Phylum',             'dependency security assesment',     true),
('Immunant',           'system software consultancy',       false),
('Toyota Connected',   'car safety and automation systems', false),
('Estuary',            'data integration',                  true),
('dbt Labs',           'raw data analysis',                 true),
('One Signal',         'communcation method agnostic crm',  true),
('Ntropy',             'financial transactions API',        true),
('Discord',            'chat',                              false),
('LogDNA',             'centralized loggin',                true),
('StackBlitz',         'browser-based development',         true),
('Disney Streaming',   'disney streaming',                 false);