cache_max_map_size: 10737418240
version: 1
app_name: ny-taxi-sample
connections:
  - config: !LocalStorage
      details:
        path: ./data
      tables:
        - !Table
          name: trips
          config: !Parquet
            path: trips
            extension: .parquet
    name: local_storage

sources:
  - name: trips
    table_name: trips
    connection: local_storage

endpoints:
  - name: trips
    path: /trips
    table_name: trips